### ISSUE TITLE
May I ask for the INRs of CIFAR-10 please

### ISSUE THREAD

**Issue by Aiolus-X** [AvivNavon/DWSNets#5]
Hallo dear author! Great job!
Could you please share the INRs of CIFAR-10 ? 
The computational burden is too heavy for some researches with limited resources like us.  
Thank you very much!

**Comment by AvivNavon** [comment]
Hi @Aiolus-X, the data is available [here](https://www.dropbox.com/sh/56pakaxe58z29mq/AABtWNkRYroLYe_cE3c90DXVa?dl=0).
