### ISSUE TITLE
Siren implementation discrepancies

### ISSUE THREAD

**Issue by JLuij** [AvivNavon/DWSNets#7]
Dear authors,
In #6, you note that the [inr.py](https://github.com/AvivNavon/DWSNets/blob/main/nn/inr.py) is used to create the dataset.
However, in this file, there are several discrepancies with the regular Siren specification that I do not see mentioned in your paper nor in the comments in your code.

First, 0.5 is added to the network's output. 
Second, the first layer doesn't follow a different initialisation scheme as `is_first`, though present, isn't used.
Third, the bias layer is initialised to zero, as `bias.uniform_(-w_std, w_std)` is commented out.

Are all these modifications indeed intentional? I'm asking since, with these modifications, the INRs fit way less effectively when training on FashionMNIST. In particular because in the paper early-stopping at 40 PSNR is described, suggesting that the network is able to attain such quality which I can only do when using a standard Siren implementation. I find it hard to see how these changes came about, how they are necessary and why they are not referenced to, but perhaps I'm missing something.

A follow-up question: are the images normalised to [0, 1] prior to fitting or are they normalised in some different way?

**Comment by AvivNavon** [comment]
Hi @JLuij,

Yes, this is the implementation we used. Since we released the datasets, you can either use it, or train your own datasets. For your dataset you can of course use different disgn choices for the INRs.

**Comment by JLuij** [comment]
Thanks for your quick response!
I do wonder, what moved you to these particular design choices? I.e. did a standard Siren architecture yield poorer downstream performance?

**Comment by AvivNavon** [comment]
No, we didn't do any exploration on that. We took the code from another research code base. Unfortunately, I do not recall which code base exactly 😅

**Comment by JLuij** [comment]
Okay, good to know, thank you :)
